### PR TITLE
Improve debugging for invalid response

### PR DESCRIPTION
**Pull request by VincentLanglet**
Hi @vlungusst,

I'm currently getting "error code: 1020" from ZeroBounce, but since there is no check in the deserialize method, 
- json_decode returns null
- then a foreach is done on null
- I get an error about the foreach on null

An early exception is more useful to have the correct issue.

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Friendly ping @vlungusst do you have time to take a look ? thanks

**Review by vlungusst — APPROVED** [review]

**Comment by VincentLanglet** [comment]
Thanks @vlungusst 

There is a lot of PR merged since the latest release 
https://github.com/zerobounce/zero-bounce-php-sdk-setup/compare/v1.1.3...master

Would it be ok to create a new tag ? Thanks a lot.

**Comment by VincentLanglet** [comment]
> Thanks @vlungusst
> 
> There is a lot of PR merged since the latest release [v1.1.3...master](https://github.com/zerobounce/zero-bounce-php-sdk-setup/compare/v1.1.3...master)
> 
> Would it be ok to create a new tag ? Thanks a lot.

Friendly ping @vlungusst would it be possible to make a new release ? Thanks !

**Comment by VincentLanglet** [comment]
> Thanks @vlungusst
> 
> There is a lot of PR merged since the latest release [v1.1.3...master](https://github.com/zerobounce/zero-bounce-php-sdk-setup/compare/v1.1.3...master)
> 
> Would it be ok to create a new tag ? Thanks a lot.

Friendly ping @vlungusst would it be possible to make a new release ? Thanks !

**Comment by VincentLanglet** [comment]
> Thanks @vlungusst
> 
> There is a lot of PR merged since the latest release [v1.1.3...master](https://github.com/zerobounce/zero-bounce-php-sdk-setup/compare/v1.1.3...master)
> 
> Would it be ok to create a new tag ? Thanks a lot.

Friendly ping @vlungusst would it be possible to make a new release ? Thanks !

@antonio-bigan @dancotetzb @aolariusst Does someone else have rights on this repository ?

**Comment by aolariusst** [comment]
@VincentLanglet I made a new release. Sorry about the wait. Please let me know if you see any other issues.

**Pull request merged**
